services:
  web:
    build:
      context: .
    container_name: ebaylistinator
    ports:
      - "8872:8000"
    restart: unless-stopped
networks:
  default:
    name: internal_network
    external: true