services:
  web:
    image: ghcr.io/vixcalibur/ebaylistinator:latest
    container_name: ebaylistinator
    ports:
      - "8872:8000"
    restart: unless-stopped
networks:
  default:
    name: internal_network
    external: true
